version: '3.8'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  catalog.api:
    build:
      context: ./Catalog.Api/
      dockerfile: Dockerfile
    container_name: catalog.api
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basketdb:
    image: redis
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  basket.api:
    build:
      context: ./Basket.Api/
      dockerfile: Dockerfile
    container_name: basket.api
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  discountdb:
    image: postgres
    container_name: discountdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discountdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  discount.api:
    build:
      context: ./Discount.Api/
      dockerfile: Dockerfile
    container_name: discount.api
    depends_on:
      - discountdb
    ports:
      - "8002:80"

volumes:
  mongo_data:
    driver: local
  pgdata:
    driver: local
  